### ISSUE TITLE
Several \revquote in the same line are not working

### ISSUE THREAD

**Issue by jmcolmenar** [MLopez-Ibanez/ansrev#3]
In the case you want to include two \revquote in the same line, the second is missing by the corresponding \revquotefrom.

Example that does not work:
\revquote{first}{First comment.} \revquote{second}{Second comment.}

Example that does work:
\revquote{first}{First comment.}
\revquote{second}{Second comment.}

Notice that the output of the compilation of the manuscript will be the same, since no new line is added.

**Comment by MLopez-Ibanez** [comment]
Sorry, I cannot reproduce this. Could you create an example as small as possible that shows the problem?

This is what I tried. 

* File `test-bug-3-main.tex`

```latex
\documentclass[crop=false]{standalone}
\usepackage[quotecolor=red]{revquote}
\begin{document}
\revquote{first}{First comment.} \revquote{second}{Second comment.}

\revquote{third}{First comment.}
\revquote{fourth}{Second comment.}

\end{document}
```

* File `test-bug-3.tex`

```latex
\documentclass{article}
\usepackage[hidebib=true,main={test-bug-3-main},quotecolor=blue]{ansrev}
\begin{document}
\AssociateEditor
\QA{Comment}{%
Reply:
\revquotefrom{first}\revquotefrom{second}

\revquotefrom{first}
\revquotefrom{second}

\revquotefrom{third}\revquotefrom{fourth}

\revquotefrom{third}
\revquotefrom{fourth}
}
\end{document}
```

They compile without errors and the PDFs show what I would expect.

**Comment by jmcolmenar** [comment]
I forgot to mention that I was using Overleaf. I have shared an example project with you.

**Comment by MLopez-Ibanez** [comment]
> I forgot to mention that I was using Overleaf. I have shared an example project with you.

I have replaced `ansrev.sty` and `revquote.sty with the latest version from github and there is no error now.

**Comment by jmcolmenar** [comment]
Solved. Thank you!
